### ISSUE TITLE
COISAS PARA FAZER - PARTE 1 (SETEMBRO)

### ISSUE THREAD

**Issue by dnaloco** [dnaloco/digitala#5]
# para fazer até quarta em 11/09/2016

- [x] logger
- [x] zend/config
- [x] arquivo env
- [x] cache doctrine
- [x] token csfr
- [x] acl funcionando
- [x] login sistema c/ jwt

### Após concluir as tarefas acima:
- [x] começando o sistema ERP...(começar as tarefas da  parte 2)GOTO => #7

**Comment by dnaloco** [comment]
Falta pouco...

**Comment by dnaloco** [comment]
FUCKING SESSION PROBLEM NOW!!! AFFFFFFFFFF......

```
<br />
<b>Fatal error</b>:  Uncaught Zend\Session\Exception\RuntimeException: Session validation failed in 
/home/familia/Sites/agenciadigitala.local/vendor/zendframework/zend-session/src/SessionManager.php:155

Stack trace:
#0 /home/familia/Sites/agenciadigitala.local/module/DACore/Module.php(34): Zend\Session\SessionManager-
&gt;start()
#1 /home/familia/Sites/agenciadigitala.local/module/DACore/Module.php(19): DACore\Module-&gt;bootstrapSession
(Object(Zend\Mvc\MvcEvent))
#2 [internal function]: DACore\Module-&gt;onBootstrap(Object(Zend\Mvc\MvcEvent))
#3 /home/familia/Sites/agenciadigitala.local/vendor/zendframework/zend-eventmanager/src/EventManager
.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /home/familia/Sites/agenciadigitala.local/vendor/zendframework/zend-eventmanager/src/EventManager
.php(251): Zend\EventManager\EventManager-&gt;triggerListeners('bootstrap', Object(Zend\Mvc\MvcEvent
))
#5 /home/familia/Sites/agenciadigitala.local/vendor/zendframework/zend-mvc/src/Application.php(169):
 Zend\EventManager\EventManager-&gt;triggerEvent in <b>/home/familia/Sites/agenciadigitala.local/vendor
/zendframework/zend-session/src/SessionManager.php</b> on line <b>155</b><br />
```

**Comment by dnaloco** [comment]
https://framework.zend.com/manual/2.3/en/modules/zend.cache.storage.adapter.html
